DROP TABLE IF EXISTS course_sections CASCADE;
DROP TABLE IF EXISTS courses CASCADE;

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. COURSES TABLE
-- Holds academic catalog course definitions, credits, and prerequisites.
-- ============================================================================
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(10) NOT NULL,            -- e.g., 'CHEM', 'PHYSIC', 'BIOL'
    course_number VARCHAR(10) NOT NULL,          -- e.g., '115', '114', '210L'
    credits INTEGER NOT NULL DEFAULT 3,
    description TEXT,
    gen_ed VARCHAR(50),                          -- e.g., 'Arts/Humanities', 'Natural Science', or NULL
    prerequisites JSONB DEFAULT '{}'::jsonb,     -- CNF course requirements & min_credits
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Enforce unique course keys across catalog
    CONSTRAINT unique_course_key UNIQUE (course_name, course_number)
);

-- Index for fast lookup by department and number
CREATE INDEX IF NOT EXISTS idx_courses_name_num ON courses (course_name, course_number);
-- GIN index for JSONB prerequisite evaluations
CREATE INDEX IF NOT EXISTS idx_courses_prerequisites_gin ON courses USING gin (prerequisites);


-- ============================================================================
-- 2. COURSE_SECTIONS TABLE
-- Holds active section offerings per semester with times, seats, and rooms.
-- ============================================================================
CREATE TABLE IF NOT EXISTS course_sections (
    class_code VARCHAR(20) PRIMARY KEY,          -- Primary key from registrar (e.g., '2153')
    course_name VARCHAR(10) NOT NULL,            -- e.g., 'CHEM'
    course_number VARCHAR(10) NOT NULL,          -- e.g., '115'
    section VARCHAR(10) NOT NULL,                -- e.g., '01', '02L'
    term VARCHAR(30) NOT NULL,                   -- e.g., 'Spring 2026', 'Fall 2026'
    days TEXT[] DEFAULT '{}',                    -- Native array, e.g., ARRAY['Tu', 'Th'] or ARRAY['W']
    start_time TIME,                             -- e.g., '09:30:00'
    end_time TIME,                               -- e.g., '10:45:00'
    location TEXT,                               -- e.g., 'University Hall Y02-2120' or 'Online'
    maximum_capacity INTEGER DEFAULT 0,
    enrolled INTEGER DEFAULT 0,
    instructors TEXT[] DEFAULT ARRAY['TBA'],     -- Array of instructor names
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Link back to courses table
    CONSTRAINT fk_course_sections_course 
        FOREIGN KEY (course_name, course_number) 
        REFERENCES courses (course_name, course_number) 
        ON DELETE CASCADE
);

-- Fast lookup when hydrating the term's catalog into memory
CREATE INDEX IF NOT EXISTS idx_sections_term_lookup ON course_sections (term, course_name, course_number);